# Generated by Django 5.0.2 on 2025-10-11 08:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managments', '0003_tag_article_views_article_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlesection',
            name='article',
        ),
        migrations.RemoveField(
            model_name='blockquote',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='mediaarticle',
            options={'ordering': ['order', 'created_at'], 'verbose_name': "Média d'article", 'verbose_name_plural': "Médias d'articles"},
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='managments__publish_89c4a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='managments__is_publ_36e159_idx',
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Résumé'),
        ),
        migrations.AddField(
            model_name='mediaarticle',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Légende'),
        ),
        migrations.AddField(
            model_name='mediaarticle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaarticle',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Mise en avant'),
        ),
        migrations.AddField(
            model_name='mediaarticle',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo')], default='image', max_length=10, verbose_name='Type de média'),
        ),
        migrations.AddField(
            model_name='mediaarticle',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='managments.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Contenu complet'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publié'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='managments.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de vues'),
        ),
        migrations.AlterField(
            model_name='eventmedia',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='mediaarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_article', to='managments.article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='mediaarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='mediaarticle',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='articles/videos/%Y/%m/', verbose_name='Vidéo'),
        ),
        migrations.AlterField(
            model_name='mediaarticle',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de la vidéo'),
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
        migrations.DeleteModel(
            name='ArticleSection',
        ),
        migrations.DeleteModel(
            name='Blockquote',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
