# Generated by Django 5.0.2 on 2025-10-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managments', '0004_remove_articleimage_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='description_1',
            field=models.TextField(default='', verbose_name='Première description'),
        ),
        migrations.AddField(
            model_name='article',
            name='description_2',
            field=models.TextField(blank=True, null=True, verbose_name='Deuxième description'),
        ),
        migrations.AddField(
            model_name='article',
            name='description_3',
            field=models.TextField(blank=True, null=True, verbose_name='Troisième description'),
        ),
        migrations.AddField(
            model_name='article',
            name='description_4',
            field=models.TextField(blank=True, null=True, verbose_name='Quatrième description'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Deuxième titre'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Troisième titre'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description courte'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre principal'),
        ),
    ]
