# Generated by Django 5.2.8 on 2025-11-10 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='subtitle_1',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image_main',
        ),
        migrations.RemoveField(
            model_name='service',
            name='subtitle_2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='subtitle_3',
        ),
        migrations.CreateModel(
            name='ServiceDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='Managements.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSubTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='Managements.service')),
            ],
        ),
    ]
