# Generated by Django 5.2.8 on 2025-11-11 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managements', '0002_rename_subtitle_1_service_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesubtitle',
            name='service',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['title'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Image de service', 'verbose_name_plural': 'Images de services'},
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text="Classe d'icône (ex: fas fa-icon)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='service',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Résumé'),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Légende'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Managements.service', verbose_name='Service associé'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre (optionnel)')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mise en avant')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Managements.service', verbose_name='Service associé')),
            ],
            options={
                'verbose_name': 'Section de service',
                'verbose_name_plural': 'Sections de services',
                'ordering': ['order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ServiceDescription',
        ),
        migrations.DeleteModel(
            name='ServiceSubTitle',
        ),
    ]
