# Generated by Django 4.2.10 on 2025-11-11 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Managements', '0003_remove_servicesubtitle_service_alter_service_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('object_id', models.PositiveIntegerField()),
                ('content', models.TextField(verbose_name='Contenu')),
                ('format', models.CharField(choices=[('text', 'Texte brut'), ('html', 'HTML'), ('markdown', 'Markdown')], default='text', max_length=20, verbose_name='Format')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Description',
                'verbose_name_plural': 'Descriptions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texte alternatif')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Légende')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_main', models.BooleanField(default=False, verbose_name='Image principale')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-is_main', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=500, verbose_name='Sous-titre')),
                ('style', models.CharField(choices=[('default', 'Par défaut'), ('highlight', 'Mis en évidence'), ('muted', 'Atténué')], default='default', max_length=50, verbose_name='Style')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Sous-titre',
                'verbose_name_plural': 'Sous-titres',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=255, verbose_name='Titre')),
                ('level', models.CharField(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], default='h2', max_length=2, verbose_name='Niveau de titre')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Titre',
                'verbose_name_plural': 'Titres',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='serviceimage',
            name='service',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-is_featured', 'order', 'name'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
        migrations.RemoveField(
            model_name='servicesection',
            name='content',
        ),
        migrations.RemoveField(
            model_name='servicesection',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Service en vedette'),
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='Service', max_length=255, verbose_name='Nom du service'),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text="Classe d'icône (ex: fas fa-heart)", max_length=100, null=True, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='servicesection',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Managements.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='servicesection',
            name='title',
            field=models.CharField(default='Section', max_length=255, verbose_name='Titre de la section'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['slug'], name='Managements_slug_16b7fa_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category'], name='Managements_categor_b9264a_idx'),
        ),
        migrations.DeleteModel(
            name='ServiceImage',
        ),
        migrations.AddField(
            model_name='title',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='image',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='description',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['content_type', 'object_id'], name='Managements_content_4aa101_idx'),
        ),
        migrations.AddIndex(
            model_name='subtitle',
            index=models.Index(fields=['content_type', 'object_id'], name='Managements_content_41c5b9_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['content_type', 'object_id'], name='Managements_content_7e1b49_idx'),
        ),
        migrations.AddIndex(
            model_name='description',
            index=models.Index(fields=['content_type', 'object_id'], name='Managements_content_f7142a_idx'),
        ),
    ]
