# Generated by Django 5.2.8 on 2025-11-11 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managements', '0004_description_image_subtitle_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(blank=True, verbose_name='Description courte')),
                ('full_description', models.TextField(blank=True, verbose_name='Description complète')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, help_text="Classe CSS de l'icône (ex: fas fa-icon)", max_length=50, verbose_name='Icône')),
                ('color', models.CharField(blank=True, help_text='Code couleur CSS (ex: #ff0000 ou var(--primary))', max_length=20, verbose_name='Couleur')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('display_order', models.PositiveIntegerField(default=0, help_text="Définit l'ordre d'affichage (du plus petit au plus grand)", verbose_name="Ordre d'affichage")),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône')),
                ('is_important', models.BooleanField(default=False, verbose_name='Important')),
            ],
            options={
                'verbose_name': 'Fonctionnalité',
                'verbose_name_plural': 'Fonctionnalités',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.RemoveField(
            model_name='description',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='image',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='servicesection',
            name='service',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='title',
            name='content_type',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['display_order', 'title'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='Managements_slug_16b7fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='Managements_categor_b9264a_idx',
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='order',
        ),
        migrations.RemoveField(
            model_name='service',
            name='summary',
        ),
        migrations.AddField(
            model_name='service',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text="Définit l'ordre d'affichage (du plus petit au plus grand)", verbose_name="Ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='service',
            name='external_url',
            field=models.URLField(blank=True, help_text='URL optionnelle vers une page externe pour ce service', verbose_name='Lien externe'),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description',
            field=models.TextField(blank=True, verbose_name='Description complète'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_caption',
            field=models.CharField(blank=True, max_length=255, verbose_name="Légende de l'image"),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Description courte'),
        ),
        migrations.AddField(
            model_name='service',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sous-titre'),
        ),
        migrations.AddField(
            model_name='service',
            name='subtitle_style',
            field=models.CharField(blank=True, help_text='Classe CSS optionnelle pour le style du sous-titre', max_length=50, verbose_name='Style du sous-titre'),
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Afficher ce service en évidence sur la page d'accueil", verbose_name='Mise en avant'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='Managements.category', verbose_name='Catégorie'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='service_active_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_featured'], name='service_featured_idx'),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='Managements.service', verbose_name='Service'),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ServiceSection',
        ),
        migrations.DeleteModel(
            name='Subtitle',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
