# Generated by Django 4.2.10 on 2025-11-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managements', '0006_banner_contactmessage_event_eventmedia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(default='liyokgreen@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='experience',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(default='+228 00 00 00 00', max_length=150),
        ),
    ]
