# Generated by Django 4.2.10 on 2025-11-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managements', '0007_teammember_email_teammember_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
