# Generated by Django 4.2.10 on 2025-11-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managements', '0008_teammember_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nom du service'),
        ),
    ]
