# Generated by Django 5.2.8 on 2025-11-24 15:09

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managements', '0009_delete_banner_alter_service_slug_alter_service_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='section',
            name='Service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='service',
            name='order',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='service',
            name='details_content',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Contenu Détaillé'),
        ),
        migrations.AddField(
            model_name='service',
            name='extra_content',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Contenu Supplémentaire'),
        ),
        migrations.AddField(
            model_name='service',
            name='intro_content',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Contenu Introduction'),
        ),
        migrations.AddField(
            model_name='service',
            name='main_image',
            field=models.ImageField(default='', upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='secondary_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='services/'),
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/carousel/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='Managements.service')),
            ],
        ),
    ]
