"""
Django settings for Liyok project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-eb^r5yfhc506%riqqa^r9vksbl!kl*=b(20fhy#5!^&-x37bvn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'liyok-green.onrender.com']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'managments'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Liyok.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'managments.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'Liyok.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Django Unfold Configuration
UNFOLD = {
    "SITE_TITLE": "Liyok Admin",
    "SITE_HEADER": "Liyok Administration",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: "/static/assets/img/logo.svg",
        "dark": lambda request: "/static/assets/img/logo_2.svg"
    },
    "SITE_LOGO": {
        "light": lambda request: "/static/assets/img/logo.svg",
        "dark": lambda request: "/static/assets/img/logo_2.svg"
    },
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/svg+xml",
            "href": lambda request: "/static/assets/img/favicon.png",
        },
    ],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "THEME": "auto",
    "STYLES": [
        lambda request: "/static/assets/css/style.css",
    ],
    "SCRIPTS": [
        lambda request: "/static/assets/js/main.js",
    ],
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "196 181 253",
            "500": "139 92 246",
            "600": "124 58 237",
            "700": "109 40 217",
            "800": "91 33 182",
            "900": "76 29 149",
            "950": "59 7 100",
        },
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇺🇸",
                "fr": "🇫🇷",
            },
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Navigation",
                "separator": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": "/admin/",
                    },
                ],
            },
            {
                "title": "Gestion du contenu",
                "separator": True,
                "items": [
                    {
                        "title": "Articles",
                        "icon": "article",
                        "link": "/admin/managments/article/",
                    },
                    {
                        "title": "Catégories",
                        "icon": "category",
                        "link": "/admin/managments/category/",
                    },
                    {
                        "title": "Tags",
                        "icon": "tag",
                        "link": "/admin/managments/tag/",
                    },
                    {
                        "title": "Galeries",
                        "icon": "photo_library",
                        "link": "/admin/managments/galerie/",
                    },
                    {
                        "title": "Services",
                        "icon": "build",
                        "link": "/admin/managments/service/",
                    },
                ],
            },
            {
                "title": "Événements",
                "separator": True,
                "items": [
                    {
                        "title": "Événements",
                        "icon": "event",
                        "link": "/admin/managments/event/",
                    },
                    {
                        "title": "Inscriptions",
                        "icon": "group",
                        "link": "/admin/managments/eventregistration/",
                    },
                ],
            },
            {
                "title": "Paramètres",
                "separator": True,
                "items": [
                    {
                        "title": "Paramètres du site",
                        "icon": "settings",
                        "link": "/admin/managments/sitesetting/",
                    },
                    {
                        "title": "Bannières",
                        "icon": "image",
                        "link": "/admin/managments/banner/",
                    },
                    {
                        "title": "Témoignages",
                        "icon": "chat",
                        "link": "/admin/managments/testimonial/",
                    },
                    {
                        "title": "Équipe",
                        "icon": "people",
                        "link": "/admin/managments/teammember/",
                    },
                ],
            },
            {
                "title": "Messages",
                "separator": True,
                "items": [
                    {
                        "title": "Messages de contact",
                        "icon": "email",
                        "link": "/admin/managments/contactmessage/",
                    },
                ],
            },
        ],
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
